algoritmo "semnome"
// Função :
// Autor :
// Data : 26/05/2014
// Seção de Declarações
var
nome:caractere
idade:inteiro
inicio
// Seção de Comandos
escreval("Digite seu nome:")
leia(nome)
escreval("Digite sua idade:")
leia(idade)

SE idade < 18 ENTAO
   escreva("Infelizmente voce nao pode fazer o cadastro pois é menor de idade")
SENAO
     escreval("Cadastrado com sucess. Parabéns")
     escreval("")
FIMSE
fimalgoritmo
